#server:
#  port: 9000
#useLocalCache: true
#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
#      routes:
#        - id: boot-auth #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: lb://boot-auth # lb 开启负载均衡
#          predicates:
#            - Path=/auth/**   #断言,路径相匹配的进行路由
#          filters:
#            - StripPrefix=1
